# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.10.12                  # https://pyreadiness.org/3.10
  - pip=23.2.1                      # https://pip.pypa.io/en/stable/news
  - robocorp-truststore=0.8.0       # https://prefix.dev/channels/conda-forge/packages/robocorp-truststore
  - pip:
    #- rpaframework==27.7.0         # https://rpaframework.org/releasenotes.html
    #- robocorp==1.2.4              # https://pypi.org/project/robocorp
    #- robocorp-browser==2.2.1      # https://pypi.org/project/robocorp-browser
    - robocorp-actions==0.0.2       # https://pypi.org/project/robocorp-actions
    - robocorp-action-server==0.0.5 # This only here for testing (simulates the action-server being in path)
